apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: xoten/auth-api:1.0.0
          env:
            - name: JWT_SECRET
              value: "PRFT"
            - name: AUTH_API_PORT
              value: "8000"
            - name: USERS_API_ADDRESS
              value: "http://svc-users-api.default.svc.cluster.local:8083"
     
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: svc-auth-api
  labels:
    app: auth-api
spec:
  selector:
    app: auth-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http