apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: xoten/frontend:1.0.0
          livenessProbe:
           httpGet:
            path: /health
            port: 3000
           initialDelaySeconds: 5
           periodSeconds: 5

          env:
            - name: AUTH_API_ADDRESS
              value: "http://svc-auth-api.default.svc.cluster.local:8000"
            - name: PORT
              value: "8080"
            - name: TODO_API_ADDRESS
              value: "http://svc-todo-api.default.svc.cluster.local:8082"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http