apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  labels:
    app: users-api
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: xoten/users-api:1.0.0
          env:
            - name: JWT_SECRET
              value: "PRFT"
            - name: SERVER_PORT
              value: "8083"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: svc-users-api
  labels:
    app: users-api
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: http