apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: svc-zipkin
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  type: NodePort
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: http