apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: backend
spec:
  type: NodePort
  selector:
    project: backendproject
    service: server
    version: "0.1"
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082