apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    project: backendproject
    service: server
    version: "0.1"
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http