apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: distribuidos
  labels:
   app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
         app: auth-api
         type: auth-api
  template:
    metadata:
      labels:
        app: auth-api
        type: auth-api
    spec:
     containers:
     - name: auth-api
       image: arturodiaz02/microservice-app-example-auth
       ports:
        - containerPort: 8000
       env:
       - name: REDIS_HOST
         value: redis
       - name: REDIS_PORT
         value: "6379"
       - name: REDIS_CHANNEL
         value: log_channel 
