apiVersion: v1
kind: Service
metadata:
  name: auth-nodeport
  namespace: auth
spec:
  type: NodePort
  selector:
    project: authproject
    service: authpod
    version: "0.1"
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
