apiVersion: v1
kind: Pod
metadata:
  name: authapi
  namespace: auth
  labels:
    project: authproject
    service: authpod
    version: "0.1"
spec:
  containers:
    - name: authapi
      image: daboca/auth-api:v1
      ports:
        - containerPort: 8000
      env:
          - name: JWT_SECRET
            value: PRFT
          - name: AUTH_API_PORT
            value: "8000"
          - name: USERS_API_ADDRESS
            value: http://users-service.users:8083
