apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: frontend
spec:
  type: NodePort
  selector:
    project: frontendproject
    service: client
    version: "0.1"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http

