apiVersion: v1
kind: Pod
metadata:
  name: usersapi
  namespace: users
  labels:
    project: usersproject
    service: userspod
    version: "0.1"
spec:
  containers:
    - name: usersapi
      image: daboca/users:v1
      ports:
        - containerPort: 8083
      env:
        - name: JWT_SECRET
          value: PRFT
        - name: SERVER_PORT
          value: "8083"
