apiVersion: v1
kind: ReplicationController
metadata:
  name: replication-controller-users
  namespace: users
spec:
  replicas: 1
  selector:
    project: usersproject
    service: userspod
    version: "0.1"
  template:
    metadata:
      name: usersapi
      labels:
        project: usersproject
        service: userspod
        version: "0.1"
    spec:
      containers:
        - name: usersapi
          image: daboca/users:v1
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              value: PRFT
            - name: SERVER_PORT
              value: "8083"