apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: users
spec:
  selector:
    project: usersproject
    service: userspod
    version: "0.1"
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: http